// Generated by typings
// Source: https://raw.githubusercontent.com/wxqqh/DataService/8642dca6abfcae3dd527e2368bbce87b0e889600/ux-typings/thunkify/thunkify.d.ts
declare module "thunkify" {
	
	function thunkify(fn: Function): (...args)=>any;	
	module thunkify {}

	export = thunkify;

}
